/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Variant({
  'other' : IDL.Null,
  'card' : IDL.Null,
  'cash' : IDL.Null,
  'cash2' : IDL.Null,
  'food' : IDL.Null,
  'rent' : IDL.Null,
  'utilities' : IDL.Null,
  'wages' : IDL.Null,
  'drinks' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminAuthStatus = IDL.Record({
  'principal' : IDL.Principal,
  'principalText' : IDL.Text,
  'isAuthenticated' : IDL.Bool,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'amount' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'restaurantName' : IDL.Text,
});
export const ExpenseBreakdown = IDL.Record({
  'other' : IDL.Int,
  'food' : IDL.Int,
  'rent' : IDL.Int,
  'utilities' : IDL.Int,
  'wages' : IDL.Int,
  'drinks' : IDL.Int,
});
export const IncomeBreakdown = IDL.Record({
  'cash' : IDL.Int,
  'cash2' : IDL.Int,
  'card' : IDL.Int,
});
export const MonthlyStats = IDL.Record({
  'expensesByCategory' : ExpenseBreakdown,
  'incomeByCategory' : IncomeBreakdown,
  'totalIncome' : IDL.Int,
  'totalExpenses' : IDL.Int,
  'netProfit' : IDL.Int,
});
export const DiagnosticsStats = IDL.Record({
  'nextTransactionId' : IDL.Nat,
  'totalUserProfiles' : IDL.Nat,
  'totalTransactions' : IDL.Nat,
});
export const MigrationState = IDL.Record({
  'legacyCutoffId' : IDL.Nat,
  'legacyScalingApplied' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTransaction' : IDL.Func(
      [IDL.Int, IDL.Text, IDL.Text, Category],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'editTransaction' : IDL.Func(
      [IDL.Nat, IDL.Int, IDL.Text, IDL.Text, Category],
      [],
      [],
    ),
  'getAdminAuthStatus' : IDL.Func([], [AdminAuthStatus], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerPrincipalAsText' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentMonthStats' : IDL.Func([], [MonthlyStats], ['query']),
  'getDiagnosticsStats' : IDL.Func([], [DiagnosticsStats], ['query']),
  'getLegacyScalingDiagnostics' : IDL.Func([], [MigrationState], ['query']),
  'getTransactionsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Variant({
    'other' : IDL.Null,
    'card' : IDL.Null,
    'cash' : IDL.Null,
    'cash2' : IDL.Null,
    'food' : IDL.Null,
    'rent' : IDL.Null,
    'utilities' : IDL.Null,
    'wages' : IDL.Null,
    'drinks' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminAuthStatus = IDL.Record({
    'principal' : IDL.Principal,
    'principalText' : IDL.Text,
    'isAuthenticated' : IDL.Bool,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'amount' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'restaurantName' : IDL.Text,
  });
  const ExpenseBreakdown = IDL.Record({
    'other' : IDL.Int,
    'food' : IDL.Int,
    'rent' : IDL.Int,
    'utilities' : IDL.Int,
    'wages' : IDL.Int,
    'drinks' : IDL.Int,
  });
  const IncomeBreakdown = IDL.Record({
    'cash' : IDL.Int,
    'cash2' : IDL.Int,
    'card' : IDL.Int,
  });
  const MonthlyStats = IDL.Record({
    'expensesByCategory' : ExpenseBreakdown,
    'incomeByCategory' : IncomeBreakdown,
    'totalIncome' : IDL.Int,
    'totalExpenses' : IDL.Int,
    'netProfit' : IDL.Int,
  });
  const DiagnosticsStats = IDL.Record({
    'nextTransactionId' : IDL.Nat,
    'totalUserProfiles' : IDL.Nat,
    'totalTransactions' : IDL.Nat,
  });
  const MigrationState = IDL.Record({
    'legacyCutoffId' : IDL.Nat,
    'legacyScalingApplied' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTransaction' : IDL.Func(
        [IDL.Int, IDL.Text, IDL.Text, Category],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'editTransaction' : IDL.Func(
        [IDL.Nat, IDL.Int, IDL.Text, IDL.Text, Category],
        [],
        [],
      ),
    'getAdminAuthStatus' : IDL.Func([], [AdminAuthStatus], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerPrincipalAsText' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentMonthStats' : IDL.Func([], [MonthlyStats], ['query']),
    'getDiagnosticsStats' : IDL.Func([], [DiagnosticsStats], ['query']),
    'getLegacyScalingDiagnostics' : IDL.Func([], [MigrationState], ['query']),
    'getTransactionsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
