/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAuthStatus {
  'principal' : Principal,
  'principalText' : string,
  'isAuthenticated' : boolean,
}
export type Category = { 'other' : null } |
  { 'card' : null } |
  { 'cash' : null } |
  { 'food' : null } |
  { 'rent' : null } |
  { 'utilities' : null } |
  { 'wages' : null } |
  { 'drinks' : null };
export interface DiagnosticsStats {
  'nextTransactionId' : bigint,
  'totalUserProfiles' : bigint,
  'totalTransactions' : bigint,
}
export interface ExpenseBreakdown {
  'other' : bigint,
  'food' : bigint,
  'rent' : bigint,
  'utilities' : bigint,
  'wages' : bigint,
  'drinks' : bigint,
}
export interface MigrationState {
  'legacyCutoffId' : bigint,
  'legacyScalingApplied' : boolean,
}
export interface MonthlyStats {
  'expensesByCategory' : ExpenseBreakdown,
  'totalIncome' : bigint,
  'totalExpenses' : bigint,
  'netProfit' : bigint,
}
export interface Transaction {
  'id' : bigint,
  'owner' : Principal,
  'date' : string,
  'description' : string,
  'category' : Category,
  'amount' : bigint,
}
export interface UserProfile { 'name' : string, 'restaurantName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTransaction' : ActorMethod<[bigint, string, string, Category], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'editTransaction' : ActorMethod<
    [bigint, bigint, string, string, Category],
    undefined
  >,
  'getAdminAuthStatus' : ActorMethod<[], AdminAuthStatus>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerPrincipalAsText' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentMonthStats' : ActorMethod<[], MonthlyStats>,
  'getDiagnosticsStats' : ActorMethod<[], DiagnosticsStats>,
  'getLegacyScalingDiagnostics' : ActorMethod<[], MigrationState>,
  'getTransactionsByCategory' : ActorMethod<[Category], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];